# Generated by Django 4.1 on 2022-09-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogpost_options_blogpost_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='owner',
        ),
    ]
